# Generated by Django 5.1.6 on 2025-02-06 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('funcao', models.CharField(max_length=100)),
                ('rg', models.CharField(max_length=20, unique=True)),
                ('cpf', models.CharField(max_length=20, unique=True)),
                ('cnh', models.CharField(blank=True, max_length=20, null=True)),
                ('validade_cnh', models.DateField(blank=True, null=True)),
                ('data_nascimento', models.DateField()),
                ('idade', models.IntegerField()),
                ('contato_pessoal', models.CharField(blank=True, max_length=20, null=True)),
                ('status', models.CharField(choices=[('Ativo', 'Ativo'), ('Inativo', 'Inativo')], max_length=20)),
                ('sexo', models.CharField(choices=[('Masculino', 'Masculino'), ('Feminino', 'Feminino')], max_length=10)),
                ('departamento', models.CharField(max_length=50)),
                ('admissao', models.DateField()),
                ('mobilizacao', models.DateField(blank=True, null=True)),
                ('desligamento', models.DateField(blank=True, null=True)),
                ('desmobilizacao', models.DateField(blank=True, null=True)),
                ('cracha_vale_id', models.IntegerField(blank=True, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
    ]
