# Generated by Django 5.1.6 on 2025-02-06 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0002_funcionario_foto_alter_funcionario_admissao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='admissao',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='cracha_vale_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='data_nascimento',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='desligamento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='desmobilizacao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='fotos/'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='id',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='mobilizacao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='validade_cnh',
            field=models.DateField(blank=True, null=True),
        ),
    ]
